require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'

cucumber::Rake::Task.new (:features) do |t|
  t.cucumber_opts = "-r features --format html --out output.html"
  t.cucumber_opts="--dryrun"
end